server:
  port: 10086 # 端口号
spring:
  datasource: # 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://localhost:3306/hotpot # 数据库地址
    username: root # 数据库账号
    password: 123456 # 数据库密码
  redis: # redis配置
    database: 0
    host: localhost # redis地址
    port: 6379 # redis端口号,默认6379
    password: # redis密码，默认为空
    timeout: 5000
    connect-timeout: 5000
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
springdoc: # springdoc配置
  api-docs:
    enabled: true # 是否开启API文档
    groups:
      enabled: true # 是否开启分组
    path: /v3/api-docs #API元数据访问路径,默认为/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html # swagger-ui文档访问路径,默认为/swagger-ui.html
    enabled: true # 是否开启swagger-ui
  group-configs: # 分组配置
    - group: default
      packagesToScan: org.tanghao.hotpot.controller